---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile.prod
    dry_run: true
    repo: rancher/docs
    tag: dev
  when:
    event:
    - pull_request

- name: publish-dev
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile.dev
    repo: rancher/docs
    tag: dev
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: publish-staging
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile.staging
    repo: rancher/docs
    tag: staging
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    branch:
    - staging
    event:
    - push

- name: publish-latest
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile.prod
    group: publish
    repo: rancher/docs
    tag: latest
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: publish-latest-algolia
  pull: always
  image: plugins/docker
  settings:
    context: .
    dockerfile: Dockerfile.algolia
    repo: rancher/docs
    tag: algolia
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push
