baseURL = ""
languageCode = "en-us"
title = "Rancher Labs"
theme = "rancher-website-theme"
themesDir = "node_modules"
pluralizeListTitles = false

# disableKinds = ["RSS"]
enableRobotsTXT = true

[permalinks]
  inside-pages = "/:filename/"

[[menu.main]]
identifier = "what-is-rancher"
name       = "What is Rancher"
weight     = "1"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Overview"
  url        = "/what-is-rancher/overview/"
  parent     = "what-is-rancher"
  weight     = "1"

  [[menu.main]]
  name       = "What Rancher Adds to Kubernetes"
  url        = "/what-is-rancher/what-rancher-adds-to-kubernetes/"
  parent     = "what-is-rancher"
  weight     = "2"

  [[menu.main]]
  name       = "How is Rancher Different"
  url        = "/what-is-rancher/how-is-rancher-different/"
  parent     = "what-is-rancher"
  weight     = "3"


  [[menu.main]]
  name       = "Run Kubernetes Anywhere"
  url        = "/kubernetes/"
  parent     = "what-is-rancher"
  weight     = "4"

  [[menu.main]]
  # name       = "Cluster Operation"
  # url        = "/what-is-rancher/cluster-operation/"
  # parent     = "what-is-rancher"
  # weight     = "5"

  [[menu.main]]
  # name       = "Hybrid cloud & multi-cloud"
  # url        = "/what-is-rancher/hybrid-cloud-and-multi-cloud/"
  # parent     = "what-is-rancher"
  # weight     = "6"

  [[menu.main]]
  # name       = "Security & compliance"
  # url        = "/what-is-rancher/security-and-compliance/"
  # parent     = "what-is-rancher"
  # weight     = "7"

  [[menu.main]]
  # name       = "Workload Management"
  # url        = "/what-is-rancher/workload-management/"
  # parent     = "what-is-rancher"
  # weight     = "8"

  [[menu.main]]
  # name       = "100% Open Source"
  # url        = "/what-is-rancher/open-souce/"
  # parent     = "what-is-rancher"
  # weight     = "9"


[[menu.main]]
identifier = "products"
name       = "Products"
weight     = "2"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Rancher"
  url        = "/what-is-rancher/overview/"
  parent     = "products"

  [[menu.main]]
  name       = "RancherOS"
  url        = "/rancher-os/"
  parent     = "products"


[[menu.main]]
#identifier = "customers"
#name       = "Customers"
#url        = "/customers/"
#weight     = "3"

[[menu.main]]
identifier = "learn"
name       = "Learn"
weight     = "4"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "Blog"
  url        = "/blog/"
  parent     = "learn"

  [[menu.main]]
  name       = "Rancher Docs"
  url        = "http://rancher.com/docs/rancher/v2.0/en/"
  parent     = "learn"

  [[menu.main]]
  name       = "RancherOS Docs"
  url        = "http://rancher.com/docs/os/v1.2/en/"
  parent     = "learn"

  [[menu.main]]
  name       = "Trainings"
  #url       = "/categories/training/"
  url        = "/training/"
  parent     = "learn"

  [[menu.main]]
  name       = "Forums"
  url        = "https://forums.rancher.com/"
  parent     = "learn"
  pre        = "<i class='material-icons'>launch</i>"

  [[menu.main]]
  #name       = "Learning Resources"
  #url        = "/learning-resources/"
  #parent     = "learn"



[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about/"
weight     = "5"
pre        = "<i class='material-icons'>keyboard_arrow_down</i>"

  [[menu.main]]
  name       = "About Us"
  url        = "/about/"
  parent     = "about"

  [[menu.main]]
  name       = "Careers"
  url        = "/careers/"
  parent     = "about"

  [[menu.main]]
  name       = "Contact Us"
  url        = "/contact/"
  parent     = "about"

  [[menu.main]]
  name       = "Events"
  url        = "/events/"
  parent     = "about"

  [[menu.main]]
  name       = "Partners"
  url        = "/partners/"
  parent     = "about"





#footer menu#
[[menu.footer]]
identifier = "about"
pre = "<i class='material-icons'>info_outline</i>"
name       = "About"
url        = "/about/"

[[menu.footer]]
identifier = "contact"
pre = "<i class='material-icons'>chat_bubble_outline</i>"
name       = "Contact"
url        = "/contact/"

[[menu.footer]]
identifier = "privacy"
pre = "<i class='material-icons'>fingerprint</i>"
name       = "Privacy"
url        = "/privacy/"

[[menu.footer]]
identifier = "careers"
pre = "<i class='material-icons'>people_outline</i>"
name       = "Careers"
url        = "/careers/"
